name: NoEndCrystals
main: lol.hyper.noendcrystals.NoEndCrystals
author: "hyperdefined"
version: "1.0"
api-version: "1.15"
commands:
  noendcrystals:
    usage: /noendcrystals
    description: Main command.
permissions:
  noendcrystals.reload:
    description: Reload configuration.
    default: op